# for every tile with at least two copies, add a fifth copy
# generated by chatgpt
def extend_four:
  reduce .[] as $item (
    {result: [], group: [], last: null};  # Initial empty result, group, and last item
    if .last == $item then
      # Still accumulating the same item
      {result: .result, group: (.group + [$item]), last: $item}
    else
      # New item detected or end of array
      if .group | length >= 2 then
        # Extend group when exactly four items
        {result: (.result + .group + [.group[0]]), group: [$item], last: $item}
      else
        # Just append the group as is
        {result: (.result + .group), group: [$item], last: $item}
      end
    end
  ) | .result + .group + (if .group | length == 4 then [.group[0]] else [] end);  # Handle last group

.after_initialization.actions += [["add_rule", "Wall", "(Fifth Tile) There is a fifth copy of every standard tile.", -99]]
|
.wall |= extend_four
