defmodule Mix.Tasks.GenerateTileTable do
  alias RiichiAdvanced.Constants
  use Mix.Task
  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("app.start")
    entries = Constants.to_tile()
    |> Enum.reject(fn {str, _atom} -> is_atom(str) end)
    |> Enum.map(fn {str, atom} -> {str, Constants.to_prime(atom)} end)
    atom_decls = entries
    |> Enum.map(fn {str, _prime} -> "  tile#{fix(str)} = \"#{str}\"," end)
    |> Enum.join("\n")
    phf_decls = entries
    |> Enum.map(fn {str, prime} -> "  \"#{str}\" => #{prime}," end)
    |> Enum.join("\n")
    fn_decls = entries
    |> Enum.map(fn {str, _prime} -> "  \"#{str}\" => tile#{fix(str)}," end)
    |> Enum.join("\n")
    ordering = Constants.ordering()
    |> Enum.map(fn {from, to} ->  "  #{Constants.to_prime(from)}u32 => #{Constants.to_prime(to)}," end)
    |> Enum.join("\n")
    ordering_r = Constants.ordering_r()
    |> Enum.map(fn {from, to} ->  "  #{Constants.to_prime(from)}u32 => #{Constants.to_prime(to)}," end)
    |> Enum.join("\n")
    shift_suit = Constants.shift_suit()
    |> Enum.map(fn {from, to} ->  "  #{Constants.to_prime(from)}u32 => #{Constants.to_prime(to)}," end)
    |> Enum.join("\n")
    shift_suit_r = Constants.shift_suit_r()
    |> Enum.map(fn {from, to} ->  "  #{Constants.to_prime(from)}u32 => #{Constants.to_prime(to)}," end)
    |> Enum.join("\n")
    File.write!("native/riichiadvanced_match/src/tile_table.rs", """
    // Generated by `generate_tile_table.ex` using values from `constants.ex`
    // Clear the file and run `mix generate_tile_table` to regenerate
    use crate::types::Prime;
    rustler::atoms! {
    #{atom_decls}
    }
    pub static TILE_TABLE: phf::Map<&'static str, Prime> = phf::phf_map! {
    #{phf_decls}
    };
    pub static ATOM_TABLE: phf::Map<&'static str, fn() -> rustler::Atom> = phf::phf_map! {
    #{fn_decls}
    };
    pub static ORDERING: phf::Map<Prime, Prime> = phf::phf_map! {
    #{ordering}
    };
    pub static ORDERING_R: phf::Map<Prime, Prime> = phf::phf_map! {
    #{ordering_r}
    };
    pub static SHIFT_SUIT: phf::Map<Prime, Prime> = phf::phf_map! {
    #{shift_suit}
    };
    pub static SHIFT_SUIT_R: phf::Map<Prime, Prime> = phf::phf_map! {
    #{shift_suit_r}
    };
    """)
  end
  def fix(str) do
    str
    |> String.replace("'", "_q_")
    |> String.replace("`", "_g_")
    |> String.replace("^", "_c_")
  end
end
