defmodule RiichiAdvancedWeb.GettextHints do
  use Gettext, backend: RiichiAdvancedWeb.Gettext
  import RiichiAdvancedWeb.Translations

  def gettext_hints do
    # messages
    t_noop("Welcome to Riichi Advanced!")
    t_noop("Player")
    t_noop("Player %{nickname} joined as %{seat}")
    t_noop("east")
    t_noop("south")
    t_noop("west")
    t_noop("north")
    t_noop("exited")
    t_noop("called %{call} on %{tile} with hand %{hand}")
    t_noop("discarded %{tile}")
    t_noop("from hand")
    t_noop("scored a %{score}-point hand")
    t_noop("declared riichi")
    t_noop("called %{call}")
    t_noop("called %{call} on %{tile} with %{choice}")
    t_noop("called %{call} on %{tile}")

    # rules tabs
    t_noop("Rules")
    t_noop("1 Han")
    t_noop("2 Han")
    t_noop("3 Han")
    t_noop("4 Han")
    t_noop("5 Han")
    t_noop("Yakuman")

    # buttons
    t_noop("Chii")
    t_noop("Pon")
    t_noop("Kan")
    t_noop("Ankan")
    t_noop("Riichi")
    t_noop("Ron")
    t_noop("Tsumo")
    t_noop("Open Riichi")
    t_noop("Chow")
    t_noop("Pong")
    t_noop("Pung")
    t_noop("Kong")
    t_noop("Mah Jongg")

    # win screen stuff
    t_noop("Discard")
    t_noop("Draw")
    t_noop("Mangan")
    t_noop("Haneman")
    t_noop("Baiman")
    t_noop("Sanbaiman")
    t_noop("Kazoe Yakuman")
    t_noop("Han")
    t_noop("Fu")
    t_noop("Double Ron")
    t_noop("Triple Ron")
    t_noop("Sanchahou")
    t_noop("Ryuukyoku")

    # yaku
    t_noop("Riichi")
    t_noop("Tsumo")
    t_noop("Ippatsu")
    t_noop("Chankan")
    t_noop("Rinshan")
    t_noop("Haitei")
    t_noop("Houtei")
    t_noop("Pinfu")
    t_noop("Tanyao")
    t_noop("Iipeikou")
    t_noop("Seat Wind")
    t_noop("Round Wind")
    t_noop("Haku")
    t_noop("Hatsu")
    t_noop("Chun")
    t_noop("Double Riichi")
    t_noop("Chiitoitsu")
    t_noop("Chanta")
    t_noop("Ittsu")
    t_noop("Sanshoku")
    t_noop("Sanshoku Doukou")
    t_noop("Sankantsu")
    t_noop("Toitoi")
    t_noop("Sanankou")
    t_noop("Shousangen")
    t_noop("Honroutou")
    t_noop("Ryanpeikou")
    t_noop("Junchan")
    t_noop("Honitsu")
    t_noop("Chinitsu")
    t_noop("Renhou")
    t_noop("Tenhou")
    t_noop("Chiihou")
    t_noop("Daisangen")
    t_noop("Suuankou")
    t_noop("Suuankou Tanki")
    t_noop("Tsuuiisou")
    t_noop("Ryuuiisou")
    t_noop("Junsei Ryuuiisou")
    t_noop("Chinroutou")
    t_noop("Chuurenpoutou")
    t_noop("Junsei Chuurenpoutou")
    t_noop("Kokushi Musou")
    t_noop("Kokushi Musou Juusan Menmachi")
    t_noop("Daisuushii")
    t_noop("Shousuushii")
    t_noop("Suukantsu")
    t_noop("Dora")
    t_noop("Ura")
    t_noop("Aka")
    t_noop("Pei")
    t_noop("Tsubame Gaeshi")
    t_noop("Shiiaru Raotai")
    t_noop("Kanburi")
    t_noop("Sangen Chiitoitsu")
    t_noop("Suushi Chiitoitsu")
    t_noop("Daichisei")
    t_noop("Uushin Tsuukan")
    t_noop("Sanrenkou")
    t_noop("Sanshoku Ittsu")
    t_noop("Kyandonhou")
    t_noop("Ryandoukou")
    t_noop("Choupaikou")
    t_noop("Sujipaikou")
    t_noop("Chousankou")
    t_noop("Sanshoku Choupaikou")
    t_noop("Sanshoku Sujipaikou")
    t_noop("Sanshoku Chousankou")
    t_noop("Suuzuukou")
    t_noop("Open Riichi")
    t_noop("Open Double Riichi")
    t_noop("Isshoku Sanjun")
    t_noop("Sanpuukou")
    t_noop("Uumensai")
    t_noop("Renkaihou")
    t_noop("Ittsu Chanta")
    t_noop("Ittsu Junchan")
    t_noop("Tanfonhou")
    t_noop("Chintanfon")
    t_noop("Chinpeikou")
    t_noop("Renhou")
    t_noop("Kinkei Dokuritsu")
    t_noop("Touchao Hanchanshue")
    t_noop("Uupin Kaihou")
    t_noop("Ryanzou Chankan")
    t_noop("Iipin Mouyue")
    t_noop("Chuupin Raoyui")
    t_noop("Shanron Chonchu")
    t_noop("Chiishin Uushii")
    t_noop("Maneshi Mangan")
    t_noop("Paarenchan")
    t_noop("Ishino Uenimo Sannan")
    t_noop("Toukanhou")
    t_noop("Shiisanpuutaa")
    t_noop("Shiisanuushi")
    t_noop("Suurenkou")
    t_noop("Suuchoupaikou")
    t_noop("Daisharin")
    t_noop("Daichikurin")
    t_noop("Daisuurin")
    t_noop("Shousharin")
    t_noop("Shouchikurin")
    t_noop("Shousuurin")
    t_noop("Isshoku Yonjun")
    t_noop("Hyakuman Goku")
    t_noop("Kachoufuugetsu")
    t_noop("Fuukasetsugetsu")
    t_noop("Kouitten")
    t_noop("Benikujaku")
    t_noop("Kokuiisou")
    t_noop("Ryuuiisourin")
    t_noop("Kouittenrin")
    t_noop("Golden Gate Bridge")
    t_noop("American Civil War")
    t_noop("Tohoku Expressway")
    t_noop("Tohoku Shinkansen")
    t_noop("Blue Tunnel")
    t_noop("Chinryuusou")
    t_noop("Chousangen")
    t_noop("Chousuushii")
  end
end
