defmodule RiichiAdvancedWeb.GettextHints do
  use Gettext, backend: RiichiAdvancedWeb.Gettext
  import RiichiAdvancedWeb.Translations

  def gettext_hints do
    # boolean values for mod config
    t_noop("true")
    t_noop("false")

    # seat values
    t_noop("east")
    t_noop("south")
    t_noop("west")
    t_noop("north")

    # rules tabs
    t_noop("Rules")
    t_noop("1 Han")
    t_noop("2 Han")
    t_noop("3 Han")
    t_noop("4 Han")
    t_noop("5 Han")
    t_noop("1 Fan")
    t_noop("2 Fan")
    t_noop("3 Fan")
    t_noop("4 Fan")
    t_noop("5 Fan")
    t_noop("6 Fan")
    t_noop("7 Fan")
    t_noop("8 Fan")
    t_noop("9 Fan")
    t_noop("10 Fan")
    t_noop("11 Fan")
    t_noop("12 Fan")
    t_noop("13 Fan")
    t_noop("Yakuman")

    # buttons
    t_noop("Chii")
    t_noop("Pon")
    t_noop("Kan")
    t_noop("Ankan")
    t_noop("Riichi")
    t_noop("Ron")
    t_noop("Tsumo")
    t_noop("Open Riichi")
    t_noop("Chow")
    t_noop("Pong")
    t_noop("Pung")
    t_noop("Kong")
    t_noop("Mah Jongg")

    # win screen stuff
    t_noop("Discard")
    t_noop("Draw")
    t_noop("Mangan")
    t_noop("Haneman")
    t_noop("Baiman")
    t_noop("Sanbaiman")
    t_noop("Kazoe Yakuman")
    t_noop("Han")
    t_noop("Fu")
    t_noop("Double Ron")
    t_noop("Triple Ron")
    t_noop("Sanchahou")
    t_noop("Ryuukyoku")
    t_noop("Nagashi Mangan")
    t_noop("Nagashi Yakuman")

    # yaku
    t_noop("Riichi")
    t_noop("Tsumo")
    t_noop("Ippatsu")
    t_noop("Chankan")
    t_noop("Rinshan")
    t_noop("Haitei")
    t_noop("Houtei")
    t_noop("Pinfu")
    t_noop("Tanyao")
    t_noop("Iipeikou")
    t_noop("Seat Wind")
    t_noop("Round Wind")
    t_noop("Haku")
    t_noop("Hatsu")
    t_noop("Chun")
    t_noop("Double Riichi")
    t_noop("Chiitoitsu")
    t_noop("Chanta")
    t_noop("Ittsu")
    t_noop("Sanshoku")
    t_noop("Sanshoku Doukou")
    t_noop("Sankantsu")
    t_noop("Toitoi")
    t_noop("Sanankou")
    t_noop("Shousangen")
    t_noop("Honroutou")
    t_noop("Ryanpeikou")
    t_noop("Junchan")
    t_noop("Honitsu")
    t_noop("Chinitsu")
    t_noop("Renhou")
    t_noop("Tenhou")
    t_noop("Chiihou")
    t_noop("Daisangen")
    t_noop("Suuankou")
    t_noop("Suuankou Tanki")
    t_noop("Tsuuiisou")
    t_noop("Ryuuiisou")
    t_noop("Junsei Ryuuiisou")
    t_noop("Chinroutou")
    t_noop("Chuurenpoutou")
    t_noop("Junsei Chuurenpoutou")
    t_noop("Kokushi Musou")
    t_noop("Kokushi Musou Juusan Menmachi")
    t_noop("Daisuushii")
    t_noop("Shousuushii")
    t_noop("Suukantsu")
    t_noop("Dora")
    t_noop("Ura")
    t_noop("Aka")
    t_noop("Pei")
    t_noop("Tsubame Gaeshi")
    t_noop("Shiiaru Raotai")
    t_noop("Kanburi")
    t_noop("Sangen Chiitoitsu")
    t_noop("Suushi Chiitoitsu")
    t_noop("Daichisei")
    t_noop("Uushin Tsuukan")
    t_noop("Sanrenkou")
    t_noop("Sanshoku Ittsu")
    t_noop("Kyandonhou")
    t_noop("Ryandoukou")
    t_noop("Choupaikou")
    t_noop("Sujipaikou")
    t_noop("Chousankou")
    t_noop("Sanshoku Choupaikou")
    t_noop("Sanshoku Sujipaikou")
    t_noop("Sanshoku Chousankou")
    t_noop("Suuzuukou")
    t_noop("Open Riichi")
    t_noop("Open Double Riichi")
    t_noop("Isshoku Sanjun")
    t_noop("Sanpuukou")
    t_noop("Uumensai")
    t_noop("Renkaihou")
    t_noop("Ittsu Chanta")
    t_noop("Ittsu Junchan")
    t_noop("Tanfonhou")
    t_noop("Chintanfon")
    t_noop("Chinpeikou")
    t_noop("Renhou")
    t_noop("Kinkei Dokuritsu")
    t_noop("Touchao Hanchanshue")
    t_noop("Uupin Kaihou")
    t_noop("Ryanzou Chankan")
    t_noop("Iipin Mouyue")
    t_noop("Chuupin Raoyui")
    t_noop("Shanron Chonchu")
    t_noop("Chiishin Uushii")
    t_noop("Maneshi Mangan")
    t_noop("Paarenchan")
    t_noop("Ishino Uenimo Sannen")
    t_noop("Toukanhou")
    t_noop("Shiisanpuutaa")
    t_noop("Shiisanuushi")
    t_noop("Suurenkou")
    t_noop("Suuchoupaikou")
    t_noop("Daisharin")
    t_noop("Daichikurin")
    t_noop("Daisuurin")
    t_noop("Shousharin")
    t_noop("Shouchikurin")
    t_noop("Shousuurin")
    t_noop("Isshoku Yonjun")
    t_noop("Hyakuman Goku")
    t_noop("Kachoufuugetsu")
    t_noop("Fuukasetsugetsu")
    t_noop("Kouitten")
    t_noop("Benikujaku")
    t_noop("Kokuiisou")
    t_noop("Ryuuiisourin")
    t_noop("Kouittenrin")
    t_noop("Golden Gate Bridge")
    t_noop("American Civil War")
    t_noop("Tohoku Expressway")
    t_noop("Tohoku Shinkansen")
    t_noop("Blue Tunnel")
    t_noop("Chinryuusou")
    t_noop("Chousangen")
    t_noop("Chousuushii")
  end

  def constant_hints do
    # rulesets
    t_noop("Riichi")
    t_noop("Sanma")
    t_noop("Space Mahjong")
    t_noop("Cosmic Riichi")
    t_noop("Galaxy Mahjong")
    t_noop("Kansai Sanma")
    t_noop("Chinitsu")
    t_noop("Minefield")
    t_noop("Sakicards v1.3")
    t_noop("Hong Kong")
    t_noop("Sichuan Bloody")
    t_noop("MCR")
    t_noop("Taiwanese")
    t_noop("Bloody 30-Faan Jokers")
    t_noop("American (NMJL)")
    t_noop("Vietnamese")
    t_noop("Malaysian")
    t_noop("Singaporean")
    t_noop("Chinese Classical")
    t_noop("Fuzhou")
    t_noop("Tianjin")
    t_noop("Ningbo")
    t_noop("Hefei")
    t_noop("Zung Jung")
    t_noop("Custom")
    t_noop("Filipino")
    t_noop("Visayan")
    t_noop("Changsha")
    t_noop("Shenyang")
    t_noop("Korean")
    t_noop("British")
    t_noop("Italian")
    t_noop("Dutch")
    t_noop("German")
    t_noop("French")
    t_noop("Australian")
    t_noop("The classic riichi ruleset, now with an assortment of mods to pick and choose at your liking.")
    t_noop("Three-player Riichi.")
    t_noop("Riichi, but sequences can wrap (891, 912), and you can make sequences from winds and dragons. In addition, you can chii from any direction, and form open kokushi (3 han).")
    t_noop("A Space Mahjong variant with mixed triplets, more yaku, and more calls.")
    t_noop("Riichi, but one of each tile is replaced with a blue galaxy tile that acts as a wildcard of its number. Galaxy winds are wind wildcards, and galaxy dragons are dragon wildcards.")
    t_noop("Sanma, but you draw until the last visible dora indicator. In addition, all fives are akadora, fu is fixed at 30, there is no tsumo loss, and scores are rounded to the nearest 1000. Flowers act as nukidora in place of north winds, which are now yakuhai. Exhaustive draws in south round always result in a repeat regardless of who's tenpai.")
    t_noop("Two-player variant where the only tiles are bamboo tiles. Try not to chombo!")
    t_noop("Two-player variant where you start with 34 tiles to make a mangan+ hand, and your remaining tiles are your discards.")
    t_noop("Riichi, but everyone gets a different Saki power, which changes the game quite a bit. Some give you bonus han every time you use your power. Some let you recover dead discards. Some let you swap tiles around the entire board, including the dora indicator.")
    t_noop("Hong Kong Old Style mahjong. Three point minimum, everyone pays for a win, and win instantly if you have seven flowers.")
    t_noop("Sichuan Bloody mahjong. Trade tiles, void a suit, and play until three players win (bloody end rules).")
    t_noop("Mahjong Competition Rules. Has a scoring system of a different kind of complexity than Riichi.")
    t_noop("16-tile mahjong with riichi mechanics.")
    t_noop("Bloody end rules mahjong, with Vietnamese jokers, and somehow more yaku than MCR.")
    t_noop("American Mah-Jongg. Assemble hands with jokers, and declare other players' hands dead. Rules are slightly different from MJME (see rules page).")
    t_noop("Mahjong with eight differently powerful joker tiles.")
    t_noop("Three-player mahjong with 16 flowers, a unique joker tile, and instant payouts.")
    t_noop("Mahjong with various instant payouts and various unique ways to get penalized by pao.")
    t_noop("Mahjong but every pung and kong gives you points, and every hand pattern doubles your points.")
    t_noop("16-tile mahjong with a version of dora that doesn't give you han, but becomes a unique winning condition by itself.")
    t_noop("Mahjong except the dora indicator actually indicates joker tiles.")
    t_noop("Includes Tianjin mahjong joker tiles, but adds more yaku and played with a 4-tai minimum.")
    t_noop("Mahjong with no honor tiles, but you must have at least eight tiles of a single suit to win.")
    t_noop("Mahjong with an additive (rather than multiplicative) scoring system.")
    t_noop("Create and play your own custom ruleset.")
    t_noop("16-tile mahjong where all honor tiles are flower tiles.")
    t_noop("16-tile mahjong where you can form dragon and wind sequences.")
    t_noop("Mahjong, but every win gets two chances at ura dora. However, a standard hand must have a pair of 22, 55, or 88.")
    t_noop("Mahjong, but every hand must be open, contain every suit, contain a terminal/honor, and contain either a triplet, kan, or dragon pair.")
    t_noop("Like Riichi but with a two-han minimum. There is also a side race to see who reaches three wins first.")
    t_noop("No description provided.")

    # tutorials
    t_noop("Basic flow of the game")
    t_noop("Calling tiles")
    t_noop("Differences from four-player")
    t_noop("Intro to space mahjong")
    t_noop("Intro to cosmic mahjong")
    t_noop("Intro to galaxy mahjong")
    t_noop("Milky Way")
  end

end
